### ISSUE TITLE
index not created from multiline text in textarea field

### ISSUE THREAD

**Issue by hirisov** [rainlab/translate-plugin#348] opened 2018-02-06 21:58 UTC
My model has a field defined this way:

        lyrics:
            label: 'Lyrics'
            size: giant
            span: auto
            type: textarea

and in the model this field is translatable and set to have an index:

  /**
  * @var array Attributes that support translation, if available.
  */
  public $translatable = [ ['lyrics', 'index'=>true] ];

If i swicth to a non default localea on the backend and enter a multiline text in this textarea field, no entry gets inserted into rainlab_translate_indexes table. If i only write a text without linebreaks in this field, then it gets saved properly. I simply use ENTER key in the textarea to add line breaks.

**Comment by munxar** [comment] 2018-02-07 06:08
I tried to reproduce it, but in my setup it works as it should.
OctoberCMS 431
RainLab.Translate 1.3.8
My database column is of type text, UTF-8.
Try to update your versions and post the db schema type.
what version of db do you use?

**Comment by hirisov** [comment] 2018-02-07 07:31
Further testinng shows it's only an issue in my development Windows environment (Windows 10, wampserver 3.1.0, OCMS 431, RainLab.Translate 1.3.8, UTF-8 database), but it works correctly on the testing Linux environment. Can somebody please test in windows environment?

**Comment by mjauvin** [comment] 2019-05-05 16:14
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Closed by mjauvin** 2019-05-05 16:14 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug
