### ISSUE TITLE
Translation with pluck not working?

### ISSUE THREAD

**Issue by RodrigoGalter** [rainlab/translate-plugin#501] opened 2019-07-26 18:28 UTC
I'm trying to get a list with ->pluck(' title ', ' term '), but this does not come with the translated values, and sometimes using ->get([' title ', ' term ']) also does not work.

**Comment by mjauvin** [comment] 2019-07-27 19:32
@RodrigoGalter can you give more details on how to reproduce this and exactly what results you are expecting?

**Comment by RodrigoGalter** [comment] 2019-07-28 14:52
Sure.

       //Language = en

        CategoriesTranslations::pluck('value', 'term')->toArray();
        CategoriesTranslations::pluck('value', 'term');
        //Replied in Portuguese
        /**
         * array:12 [▼
         * "data" => "Data"
         * "diario" => "Diário"
         * "ena" => "Ena BR"
         * "subsistema" => "Subsistema"
         * "sin" => "SIN"
         * "carga" => "Carga"
         * "ons" => "ONS"
         * "ear" => "EAR"
         * "megawhat" => "MegaWhat"
         * "se-co" => "SE/CO"
         * "pld" => "PLD"
         * "semanal" => "Semanal"
         * ]
         */

        CategoriesTranslations::get(['value', 'term'])->toArray();
        //Replied in Portuguese
        /**
         * 0 => array:2 [▼
         * "value" => "Data"
         * "term" => "data"
         * ]
         * 1 => array:2 [▼
         * "value" => "Diário"
         * "term" => "diario"
         * ]
         * 2 => array:2 [▼
         * "value" => "Ena BR"
         * "term" => "ena"
         * ]
         * ...
         */

        CategoriesTranslations::get()->toArray();
        //Replied as expected
        /**
         * 0 => array:3 [
         * "id" => 1
         * "term" => "data"
         * "value" => "Date"
         * ]
         * 1 => array:3 [
         * "id" => 2
         * "term" => "diario"
         * "value" => "Daily"
         * ]
         * 2 => array:3 [
         * "id" => 3
         * "term" => "ena"
         * "value" => "Ena EN"
         * ]
         * ...
         */

**Comment by RodrigoGalter** [comment] 2019-08-20 18:10
Any news?

**Comment by RodrigoGalter** [comment] 2019-08-20 18:42
I noticed that non-translation occurs when applying a select.

**Comment by daftspunk** [comment] 2023-06-07 01:33
For posterity, this issue is addressed in OCMS v3 using the [Multisite trait](https://docs.octobercms.com/3.x/extend/database/traits.html#multisite) since attributes are intrinsically available.

**Closed by daftspunk** 2023-06-07 01:33 UTC
Labels: Priority: Low, Type: Conceptual Enhancement, help wanted
