### ISSUE TITLE
Translations not working on relation modal pop-ups on update only on create

### ISSUE THREAD

**Issue by getrightnl** [rainlab/translate-plugin#242] opened 2017-03-29 13:31 UTC
The translations are working on creation, but not when I update the field the field the translated string is empty. It is for a relationship which is defined in a new tab. The translation is not saved when you try to update a record, but it is when it is created the first time it is.

Also when I edit a new created item with two translations inside of them and I try to edit the translation, the old one stays and is not updated.

I checked the formdata in my console, the right form data is submitted but not updated in the rainlab_translate_attributes table. Looks like a problem with relationship.

Does anyone has a clue why this happens. 

See screenshot below

![image](https://cloud.githubusercontent.com/assets/16100278/24456886/b59fc8b4-1494-11e7-97ae-65b4d7d64ea2.png)

**Comment by alexaxhauck** [comment] 2017-04-04 09:50
i was just going to github and file this issue...
so the same issue here. when working with relations the table is not filled. only a empty json string is inserted like: {"headline":"","memo":""}

**Comment by LevMax** [comment] 2017-04-04 09:52
Hello! I have almost the same question.
I try to add translations for upload images title and description.
A have already added
 `
        File::extend(function ($model) {
            $model->implement[] = 'RainLab.Translate.Behaviors.TranslatableModel';
            $model->translatable = ['title', 'description'];
        });
`
and it seems to work properly but translate button haven't appear at all. 
http://joxi.ru/Dr8O1B8FeppzA6
Translation works well in my model, but not on related System\Models\File in modal forms.
Do you have so ideas, what i need to to?
Best regards, Maxim.

**Comment by Glitchbone** [comment] 2017-04-04 09:54
Hi @LevMax,
This plugin does not work with files. You can try a plugin I made to handle files title and description translation : https://github.com/Glitchbone/octobercms-filetranslate-plugin

**Comment by LevMax** [comment] 2017-04-04 10:31
Hi, @Glitchbone, and thanks! 
I have installed your plugins. All works fine, except of saving default "en" values to system_files table.
Translations in another languages are properly saved in rainlab_translate_attributes.

**Comment by getrightnl** [comment] 2017-04-10 15:37
When I save the updated model, the $this->translatableAttributes is empty inside of the function syncTranslatableAttributes() on line 220 of the plugins/rainlab/translate/classes/TranslatableBehavior.php class. 

However I'm unable to find the place where the this->translatableAttributes is set. When I save the base model where the model is related to the attributes are there.

**Comment by AugmentBLU** [comment] 2017-08-20 00:10
I'm seeing this issue with build 420, the post data looks near identical to that of updating a record via it's own page controller but in a modal popup, it's just not saving. 

Any ideas or fixes? This is quite important.

**Comment by rgsone** [comment] 2017-09-30 09:55
@AugmentBLU see #209 for a temporary fix

**Comment by LukeTowers** [comment] 2017-10-26 21:29
Duplicate of #209

**Closed by LukeTowers** 2017-10-26 21:29 UTC
Labels: Status: Review Needed, Type: Bug

**Comment by LukeTowers** [comment] 2019-03-16 04:34
Fixed by https://github.com/octobercms/october/commit/13d710b161bdf65a19f38f974c259bc4997a162c
