### ISSUE TITLE
Nested fields lost value from default lang after change language

### ISSUE THREAD

**Issue by Trysystems** [rainlab/translate-plugin#490] opened 2019-06-15 05:51 UTC
Hello!
Last October cms build, last Rainlab Translate.

JSON field like 
`content[test]:
        type: mlricheditor`
After change language or after save page, reload and save again - default language field is empty. Because helper input <input type="hidden" name="RLTranslate[en][content][test]" value="" data-locale-value="en"> has empty value.

Temporary fix: 
MLControl.php line 157: 
Change 
`elseif ($this->model->methodExists('getAttributeTranslated')) {`
to
`elseif ($this->model->methodExists('getAttributeTranslated') && $this->defaultLocale->code != $locale) {` 

Thanks Rainlab!

**Comment by mjauvin** [comment] 2019-06-15 12:47
Duplicate of #303

**Closed by mjauvin** 2019-06-15 12:48 UTC
Labels: duplicate
