### ISSUE TITLE
[Known Issue] After save add FF before text

### ISSUE THREAD

**Issue by host138** [rainlab/translate-plugin#365] opened 2018-03-30 10:21 UTC
Very frequently I see this bug. But it is not always added

**Comment by munxar** [comment] 2018-03-30 10:43
@host138 please take the time to make a descriptive bug report, otherwise I take the same time to answer.
-> 42

**Comment by LukeTowers** [comment] 2018-03-30 16:01
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

And now for the sassy response:

Very frequently I see little effort in making issue reports. But rarely do they get handled.

**Comment by mjauvin** [comment] 2019-05-11 05:53
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by pavsid** [comment] 2019-11-07 10:20
I can verify this issue, having experienced it many times I am able to decipher OP's bug report. Will gather some info but until now I haven't been able to replicate it on demand.

**Comment by mjauvin** [comment] 2019-12-18 13:05
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by pavsid** [comment] 2020-02-18 12:24
Just adding to this for the record. Still haven't managed to create a solid test case to replicate the issue, but for what it's worth, it looks like the offending piece of code is in `modules\backend\formwidgets\richeditor\assets\js\build-min.js` on line 1706...

```
if(editor.core.hasFocus()){if(!editor.core.isEmpty()){editor.selection.save();editor.$el.find('.fr-marker[data-type="true"]:first').replaceWith('<span class="fr-tmp fr-sm">F</span>');editor.$el.find('.fr-marker[data-type="false"]:last').replaceWith('<span class="fr-tmp fr-em">F</span>');}}
```

Seems that the "FF" is intentional, and is replaced with 'FROALA-SM' on line 1708, which in turn is then replaced with an empty string on line 1711. 

I can confirm that when the "FF" appears, it isn't actually visible in the editor, until you save the file, then re-open it and it's there.

So maybe the editor content is being held in a variable somewhere else, which isn't being updated by the logic on lines 1708 and 1711?

**Comment by mjauvin** [comment] 2020-03-15 19:48
@pavsid is this bug reproducible WITHOUT the Translate Plugin enabled?

**Comment by mjauvin** [comment] 2020-03-18 15:03
@daftspunk could you take a look into this since you're the only one with the actual Froala's source code?

**Comment by pavsid** [comment] 2020-03-20 11:09
> @pavsid is this bug reproducible WITHOUT the Translate Plugin enabled?

99% sure it isn't, because I have only ever noticed it happen after switching between languages in the editor.

**Comment by manuelbua** [comment] 2020-05-07 10:24
I'm also encountering this, here are the steps i follow to solidly reproduce this:

- place the cursor or make a selection in the HTML viewer
- switch to the source
- switch back to the HTML viewer
- switch to another language
- switch back to the previous language
- the "FF" appears at the cursor or at both the start and end of the selection

![](https://i.imgur.com/jucLhA4.gif)

**Comment by pavsid** [comment] 2022-04-21 17:29
Noticed this bug again yesterday - this time in OC v2.2.474 with Translate plugin v1.10.3

**Comment by daftspunk** [comment] 2023-06-07 01:27
I can confirm that this issue has been resolved in OCMS v3 and Translate v2.

**Closed by daftspunk** 2023-06-07 01:27 UTC
Labels: Type: Bug
