### ISSUE TITLE
MLMarkdownEditor not saving translated files

### ISSUE THREAD

**Issue by u-michiel** [rainlab/translate-plugin#221] opened 2017-02-06 16:41 UTC
Referencing issue #106 

I'm trying to get translations working for markdown content files (Rainlab.Pages plugin).
The plugin works well with .htm files (richtext), but not with markdown files.

After switching the editor to markdown, it reads files in multiple language correctly (e.g. I can switch between content.md and content.nl.md). It also saves any changes I make to content.md perfectly. When I try to save or edit content.{languagecode}.md it says "... has been successfully saved.", but the file doesn't update or get created if it didn't exist before (nothing gets written).

Since it works perfectly with .htm files and the richtext editor, I'm thinking this might be a bug in mlmarkdowneditor in the translate plugin?

**Comment by artras** [comment] 2017-02-06 16:56
#218 dublicate

**Comment by daftspunk** [comment] 2017-02-14 20:56
This issue lacks enough detail or the replication instructions cannot be actioned easily. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Comment by u-michiel** [comment] 2017-02-14 21:41
### Markdown content files not saving in non-default language

**Reproduce steps**

0. Have Rainlab.Pages and this plugin installed with two language enabled 
1.  In the back-end open Pages > Content section
2. Create a new Markdown file (e.g. test.md)
3. Enter some text
4. Save
5. Switch language
6. Enter some text
7. Save

**Expected behavior**

1.  Create file test.{langcode}.md
2. Save text to that file

**Actual behavior**

1. File was not created
2. And because of that text was not saved


When you create the file yourself manually (eg. test.nl.md), it reads the file correctly when switching language to NL, but saving also doesn't work

**Comment by LukeTowers** [comment] 2017-10-26 16:12
Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-26 16:12 UTC
Labels: Status: Revision Needed, Type: Unconfirmed Bug
