### ISSUE TITLE
URI translation

### ISSUE THREAD

**Issue by flo-sch** [rainlab/translate-plugin#112] opened 2016-02-10 20:14 UTC
Hey,

Small question about this plugin,
Is it possible, or is there any plan in the future to enable URI-translation?

Basically, if I have three languages, for instance "en", "fr", "de", and an about page,
I currently can access :

```
/en/about
/fr/about
/de/about
```

For SEO purposes, I would prefer to access (as the same route) :

```
/en/about
/fr/a-propos
/de/uber-uns
```

**Comment by CptMeatball** [comment] 2016-02-11 15:31
Duplicate of #25.

**Comment by Flo-Schield-Bobby** [comment] 2016-02-11 16:24
Indeed, didn't see that one, sorry.
Should I close this one?

**Comment by daftspunk** [comment] 2016-05-05 10:09
Merged with #25

**Closed by daftspunk** 2016-05-05 10:09 UTC
