### ISSUE TITLE
Problem with translated WYSIWYG Editor in Repeater

### ISSUE THREAD

**Issue by jo-bitcraft** [rainlab/translate-plugin#627] opened 2020-12-09 15:48 UTC
- OctoberCMS Build: 469
- PHP Version: 7.4
- Database Engine: MySQL
- Plugins Installed: Rainlab Translate Plugin

### Description:

If you use a translated WYSIWYG Editor in a repeater and copy&paste content i.e. from Google Spreadsheet it will add html attributes like data-sheets-userformat or data-sheets-value, i.e.

`<span data-sheets-userformat="{&quot;2&quot;:513,&quot;3&quot;:{&quot;1&quot;:2,&quot;2&quot;:&quot;#,##0.0&quot;,&quot;3&quot;:1},&quot;12&quot;:0}" data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:4}">4,0</span>
`
Those attributes causes the repeater to stop working correctly - it won't show anything in that language anymore. With the default language it seems that it escapes those attributes.

### Steps To Reproduce:

1. make a translated repeater with a Richtext-Editor
2. copy into one translation Richtext-Editor that html content
`<span data-sheets-userformat="{&quot;2&quot;:513,&quot;3&quot;:{&quot;1&quot;:2,&quot;2&quot;:&quot;#,##0.0&quot;,&quot;3&quot;:1},&quot;12&quot;:0}" data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:4}">4,0</span>`

![image](https://user-images.githubusercontent.com/52261448/101648745-6e6bba00-3a3a-11eb-93bc-350b731dbe07.png)

3. save
4. ALL repeater fields for that language (if not the default) won't show up anymore (although the content is there)

When switching to a different language the input field will be completely cleared.

![image](https://user-images.githubusercontent.com/52261448/101648266-ef768180-3a39-11eb-981b-ce487519b301.png)

**Comment by mjauvin** [comment] 2020-12-10 18:20
Duplicate of https://github.com/rainlab/translate-plugin/issues/448

**Closed** 2020-12-10 18:20 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug
