### ISSUE TITLE
Language attributes are not saved in relation popups

### ISSUE THREAD

**Issue by kharanenka** [rainlab/translate-plugin#330] opened 2018-01-11 08:21 UTC
I have a Product model. I extends it and adds morphOne relation to the Test model. I extends fields of Product model in backend and adds new relation field for Test model. Test model has translate fields. Relation field has buttons: create, update. From the product form, I create a new Test model object and set the values for the language fields immediately. The language attributes are successfully saved in the table 'rainlab_translate_attributes'. From the product form, I open popup with update form the test model and change the values of the language fields. The language attributes are not saved in the table 'rainlab_translate_attributes'. I found that $this->translatableAttributes property is empty in TranslatableBehavior::syncTranslatableAttributes() method. But why this property is cleared I did not find.

**Comment by LukeTowers** [comment] 2018-01-11 14:44
Duplicate of #209

**Closed by LukeTowers** 2018-01-11 14:44 UTC

**Comment by LukeTowers** [comment] 2019-03-16 04:34
Fixed by https://github.com/octobercms/october/commit/13d710b161bdf65a19f38f974c259bc4997a162c
