### ISSUE TITLE
Should it work with builderList and builderDetails default components?

### ISSUE THREAD

**Issue by disvst** [rainlab/translate-plugin#399] opened 2018-08-24 12:57 UTC
Sorry for this question, but from a beginner perspective, does this plugin allow translations and slug translations out of the box with theses two default components or does it require specific, custom made, components?

**Comment by LukeTowers** [comment] 2018-08-24 15:40
@disvst Have you tried it yet? It probably does, you still need to mark your model properties as translatable though.

**Comment by disvst** [comment] 2018-08-24 15:48
@LukeTowers Yes I tried, but I had an issue with the slug, which I used as a identifier and key value to link builderList and builderDetails: the record on the detail page is found only for the slug in the default language but not for the translations. 

My model properties are translatable and the slug indexed.

**Comment by munxar** [comment] 2018-08-24 16:19
check out this part in the documentation:
https://github.com/rainlab/translate-plugin#url-parameter-translation

**Comment by disvst** [comment] 2018-08-24 16:50
Thanks @munxar 

I tried it with no success. 

In plugin.php I have 

    public function boot()
        {
            Event::listen('translate.localePicker.translateParams', function($page, $params, $oldLocale,         $newLocale) {
                if ($page->baseFileName == 'your-page-filename') {
                return Job::translateParams($params, $oldLocale, $newLocale);
               }
                 });
        }

And in job.php (my model file)

    <?php namespace Anandita\Jobboard\Models;

    use Model;

    /**
     * Model
     */
    class Job extends Model
    {
        use \October\Rain\Database\Traits\Validation;

        /**
         * @var string The database table used by the model.
         */

        public $table = 'anandita_jobboard_';
        public $implement = ['RainLab.Translate.Behaviors.TranslatableModel'];

        /**
          * @var array Attributes that support translation, if available.
         */
        public $translatable = [
         'title',
        'content',
        'expertise',
        'hierarchy',
        'sector',
        'extract',
        'emphasis',
        'location',
        'type',
        ['slug', 'index' => true]
    ];

        public static function translateParams($params, $oldLocale, $newLocale) {
        $newParams = $params;
        foreach ($params as $paramName => $paramValue) {
            $records = self::transWhere($paramName, $paramValue, $oldLocale)->first();
         if ($records) {
            $records->translateContext($newLocale);
            $newParams[$paramName] = $records->$paramName;
            }
        }
        return $newParams;
    }

        /**
         * @var array Validation rules
         */
        public $rules = [
        ];

    `}`

**Comment by munxar** [comment] 2018-08-24 23:29
is the page you want to translate named 'your-page-filename' ??? this must match your pages name.
your pages parameter must be names :slug too.

**Comment by disvst** [comment] 2018-08-27 10:33
Thanks @munxar, I did actually put the right name (in my case, job-single). But I'm stuck with "record not found".

**Comment by disvst** [comment] 2018-08-29 14:57
A precision maybe: the plugin does works of course very well with custom components.

**Comment by mjauvin** [comment] 2019-05-15 18:09
@disvst I think what you are looking for is https://github.com/rainlab/translate-plugin#indexed-attributes

The BuilderDetails component uses the "->where()" method to search with the provided key, but in order to work with translation, it would need to use "->transWhere()".

Closing this now, if you need to re-open this, please do so providing new elements.

**Closed by mjauvin** 2019-05-15 18:09 UTC
Labels: Type: Question

**Comment by mjauvin** [comment] 2019-05-15 18:10
duplicate of https://github.com/rainlab/translate-plugin/issues/308
