### ISSUE TITLE
Issue when linking to my plugin record page

### ISSUE THREAD

**Issue by marcomessa** [rainlab/translate-plugin#308] opened 2017-10-25 10:25 UTC
Hello, I have a model - Content -  with the correct implementation of translatable

```php
 public $implement = ['@RainLab.Translate.Behaviors.TranslatableModel'];

    public $translatable = [
        'title',
        ['slug', 'index' => true],
        'descrizione'
    ];
```
in backend, forms are correctly displaying multi language options. To problem is when I try to access to record details page. In the configuration section i have:

`
title = "singola realizzazioni"
url = "/realizzazioni/:slug"
layout = "static"
is_hidden = 0

[viewBag]
localeUrl[en] = "/manufactorings/:slug"

[builderDetails]
modelClass = "Mmes\Contents\Models\Content"
identifierValue = "{{ :slug }}"
modelKeyColumn = "slug"
displayColumn = "slug"
notFoundMessage = "Record not found"
`

I create link to detailspage with builder component code

`<a href="{{ detailsPage|page({ (detailsUrlParameter): attribute(record, detailsKeyColumn) }) }}">`

which generate:
http://mysite.dev/translated-path/translated-slug
but it displays an empty page. 

Instead, if I switch from original details page to the translated one with te language picker, the resulti url is
http://mysite.dev/translated-path/ORIGINAL-slug 
and my trasnalted contents are displayed!

**Comment by mjauvin** [comment] 2019-05-15 17:58
Hello, first of all is the problem still occuring? It has been close to 2 years since you reported this...

If it is, can you provide a simpler example with more details on how to reproduce this?

**Comment by mjauvin** [comment] 2019-05-15 18:02
Looking at the builder plugin component code, it's using the "->where()" method using the slug... which would not return the proper value... should be "transWhere()"... so this is not a bug, you're just not using the Translate plugin properly (see https://github.com/rainlab/translate-plugin#indexed-attributes)

I'm closing this as invalid, please re-open if you think otherwise.

**Closed by mjauvin** 2019-05-15 18:02 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug
