### ISSUE TITLE
Pages menu translation bug

### ISSUE THREAD

**Issue by bbrandtlv** [rainlab/translate-plugin#213] opened 2017-01-24 14:57 UTC
Hey
Did anyone managed to translate menus in pages plugin?

Problem is known for more than year I think, but still no solution for it.

Please advice?!

Thanks

**Comment by jan-vince** [comment] 2017-01-24 19:16
I have tried @daftspunk 's method and it worked for me (rainlab/pages-plugin#222):

 * add an API code to menu item in backend
 * insert ````{{ ('nav.' ~ item.code)|_ }}```` in HTML where translated menu item should be displayed

Is this what you were looking for?

**Comment by bbrandtlv** [comment] 2017-02-08 20:34
this one is easy:
I dont understand why it cannot be added to main code.

Please do:
```

    {% for item in items if not item.viewBag.isHidden %}
    <li role="presentation" class="{{ item.isActive ? 'active' : '' }} {{ item.isChildActive ? 'child-active' : '' }} {{ item.viewBag.cssClass }}">
        {% if item.url %}
            <a href="{{ item.url }}" {{ item.viewBag.isExternal ? 'target="_blank"' }}>
                {{ item.title|_ }}
            </a>
        {% else %}
            <span>{{ item.title|_ }}</span>
        {% endif %}

        {% if item.items %}
            <ul>{% partial __SELF__ ~ "::items" items=item.items %}</ul>
        {% endif %}
    </li>
    {% endfor %}

```
{{ item.title|_ }}
this is only change i made.

**Comment by LukeTowers** [comment] 2017-03-15 19:29
Duplicate of https://github.com/rainlab/pages-plugin/issues/222, https://github.com/rainlab/pages-plugin/issues/190. Further discussion can be made in https://github.com/rainlab/pages-plugin/issues/190. There is a bounty open for the issue here: https://www.bountysource.com/issues/37969749-question-are-the-menu-items-be-translatable

**Closed by LukeTowers** 2017-03-15 19:29 UTC
