### ISSUE TITLE
Messages won't translate

### ISSUE THREAD

**Issue by schnubor** [rainlab/translate-plugin#56] opened 2015-04-08 13:54 UTC
Hey,

using this plugin for a while now and decided to update it today, because why not, it's awesome. 

Added a few more messages to be translated. They appear in the "Settings->Translate Messages" tab after scanning. Entered the translation, cleared the cache, but nothing happens. It's just using the default message, no matter what language I'm choosing (via localePicker or direct URL). Also tried to edit existing messages and they won't update as well. So I'm wondering where else they are actually cached?

Also cleared the browser cache several times just to be sure. It's weird because the setup worked in the past and all I did was updating the plugin and October. Content files are working fine for each of the languages. I'm running with October 238 right now.

Any Ideas on this?

Best,
Christian

**Comment by ar7n** [comment] 2015-04-09 11:37
same problem

**Comment by ar7n** [comment] 2015-04-09 11:51
try to cleat /storage/framework/cache

**Comment by toome123** [comment] 2015-05-03 15:00
i have same problem , I tried to erase any kind of cache, and I think the problem is not in the cache, have message won't translate .... Please if someone have response to the problem to tell us :)

**Comment by 7talents** [comment] 2015-05-11 12:48
I have the same problem. It seems the "clear cache" button is not working as it should - after I delete the folders in /storage/framework/cache manually, everything works as it should.

**Comment by untungs** [comment] 2015-06-13 14:57
I already cleared the cache manually, but messages still won't translate. Content translation is working though.

**Comment by schnubor** [comment] 2015-06-13 17:34
`php artisan cache:clear` did the job for me.

**Comment by mabasic** [comment] 2015-12-12 17:13
+1

**Comment by fresswolf** [comment] 2016-01-28 16:16
this problem still exists

**Comment by jBOKA** [comment] 2016-02-16 18:27
+1
had to artisan cache:clear as well

**Comment by flyingbaba** [comment] 2016-04-02 20:09
I have no problem with it on a local server station runing on wamp, but remote server shows only default untranslated messages in the pages or partials. Cache:clear and deleting directories not helped

**Comment by LukeTowers** [comment] 2017-10-26 15:42
Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-26 15:42 UTC
