### ISSUE TITLE
Localizations only working on CMS, not on static pages 

### ISSUE THREAD

**Issue by tbergeron** [rainlab/translate-plugin#206] opened 2016-12-30 02:52 UTC
Hi, I've been having the same bug since I started using OctoberCMS with Rainlab's stuff on edgeUpdates. This is happening on all platforms (Ubuntu / OSX / PHP 6 & 7).

Basically I noticed that all static pages *with content* have no localizations working. (i.e. We only can see 'nav.home' instead of the actual localized content). If I remove the content, the localizations come back magically. (i.e. 'nav.home' becomes 'Home' again)

*Also*, localizations work for all CMS pages. (I have a contact and products page using the CMS tab and these are all fully localized).

Both static pages and CMS use the same layout. (I also tried separating layouts with no luck)

Feel free to ask for more details. I will add a few screenshots later.
Thanks!

**Comment by Eoler** [comment] 2017-01-09 21:59
> Basically I noticed that all static pages with content have no localizations working.

Confirmed.

**Comment by daftspunk** [comment] 2017-01-09 22:05
This issue lacks enough detail or the replication instructions cannot be actioned easily. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Comment by Eoler** [comment] 2017-01-10 12:34
OctoberCMS 1.0.391, Pages 1.2.13, Translate 1.2.8

1. add two languages: EN (default and one other: HR) 
2. create a new theme
3. add layout `layouts/main.htm`
```
[localePicker]
forceUrl = 1
[staticPage]
==
<html>
<head>
    <title>{{ this.page.title }} - Test l10n</title>
</head>
<body>
    {% partial "partial10n" %}
    {% page %}
</body>
</html>
```
4. add partial `partials/partial10n.htm`
```
{{ 'Am I translated?'|_ }} {{ activeLocale }}
```
5. add static page `content/static-pages/content-page.htm`
```
[viewBag]
title = "Content page"
url = "/content-page"
layout = "main"
is_hidden = 0
navigation_hidden = 0
==
<p>Content</p>
```
6. add static page `content/static-pages/no-content-page.htm`
```
[viewBag]
title = "No content page"
url = "/no-content-page"
layout = "main"
is_hidden = 0
navigation_hidden = 0
==
```
7. translate the only available message in Settings/Translate messages

Observe (unexpected) different translations in header of the following pages:
/hr/content-page
/hr/no-content-page

**Comment by daftspunk** [comment] 2017-01-10 20:18
Duplicate of #204?

**Closed** 2017-01-10 20:19 UTC
