### ISSUE TITLE
error array_keys() expects parameter 1 to be array, object given in EventRegistry.php after edge update

### ISSUE THREAD

**Issue by Verbat** [rainlab/translate-plugin#438] opened 2019-01-07 14:58 UTC
I updated OctoberCMS and the translate Plugin (edge update enabled) to their latest version.
I had to apply the following fix https://github.com/rainlab/translate-plugin/pull/436 for the CMS pages which works fine.
I also noticed that when I try to open the Pages menu from the static Page Plugin in the backend I'll receive the following error on the line which says array_keys($locales));. 

array_keys() expects parameter 1 to be array, object given
C:\laragon\www\connect-com\plugins\rainlab\translate\classes\EventRegistry.php line 219

```
public function pruneTranslatedContentTemplates($templates)
    {
        $locales = LocaleModel::listAvailable();
        print_r($locales);
        $extensions = array_map(function($ext) {
            return '.'.$ext;
        }, array_keys($locales));
  
        return $templates->filter(function($template) use ($extensions) {
            return !Str::endsWith($template->getBaseFileName(), $extensions);
        });
    }
```
Screenshot below:
https://screenshotscdn.firefoxusercontent.com/images/1ae4663a-fc60-4783-9dca-00594ef6df82.png

**Comment by adrenth** [comment] 2019-01-07 15:17
See #439

**Comment by LukeTowers** [comment] 2019-01-07 16:19
Duplicate of #439.

**Closed by LukeTowers** 2019-01-07 16:19 UTC
Labels: Type: Bug, duplicate
