### ISSUE TITLE
AlternateHrefLangElements and LocalePicker components don't support Rainlab/Blog posts

### ISSUE THREAD

**Issue by pavsid** [rainlab/translate-plugin#468] opened 2019-04-09 17:54 UTC
There are various issues mentioning this but doesn't look like any fixes have been implemented.

The `AlternateHrefLangElements` and `LocalePicker` components seem to support Static Pages and CMS Pages, but not Blog Posts.

There must be a better way to detect a Blog Post on the current page, but this code seems to fix the issue in `AlternateHrefLangElements`...

    // rainlab/translate/components/AlternateHrefLangElements::retrieveLocalizedUrl

         /*
         * Blog Post
         */
        else if (isset($page->components['blogPost'])) {
            $post = $page->components['blogPost']->post;
            $router = new RainRouter;
            $params = $this->getRouter()->getParameters();
            $params = ['slug' => $post->lang($locale)->slug] + $params;
            $localeUrl = $router->urlFromPattern($page->url, $params);
        }

However, it won't work in `LocalePicker` due to it using AJAX and so the blogPost component won't exist.

I created my own `LocaleSelector` based on `LocalePicker` anyway which doesn't use AJAX.

Any comments on the above? Any improvement to detecting a Blog Post (which will work under AJAX too)?

**Comment by mjauvin** [comment] 2019-05-04 19:31
I confirm this.
The staticPage component from Rainlab.Pages plugin injects itself into the page's apiBag and can then be accessed from within the onSwitchLocale AJAX handler.
This is different for the Rainlab.Blog plugin somehow.

**Comment by mjauvin** [comment] 2019-05-04 20:00
You can probably use the following, but this has not been tested:

        else if ($page->hasComponent('blogPost')) {
            $component = $page->getComponent('blogPost');
             ...

**Comment by mjauvin** [comment] 2019-05-05 06:42
Duplicate of https://github.com/rainlab/translate-plugin/issues/167

**Closed by mjauvin** 2019-05-05 06:42 UTC
Labels: Priority: Medium, Type: Bug, duplicate
