### ISSUE TITLE
MLControl getLocaleValue empty on default locale if we use array field

### ISSUE THREAD

**Issue by Trysystems** [rainlab/translate-plugin#555] opened 2020-02-13 20:26 UTC
Hello! 

For a long time I have problem with translate fields like:
```
content[wework1]:
        label: 'text'
        span: left
        type: mlricheditor
```

So getAttributeTranslated function in MLControl return empty value on line 158 (because TranslatableBehavior class can't find nested key with function getAttributeFromData on line 150).

Fix for me - change string 157 in MLControl trait from:
`elseif ($this->model->methodExists('getAttributeTranslated') {` to: 
`elseif ($this->model->methodExists('getAttributeTranslated')  && $this->defaultLocale->code != $locale) {`

But with each update problem returns. Similar issue #303 from 2017 and still not solved.

**Comment by mjauvin** [comment] 2020-02-13 20:46
Can you please submit a PR for this, we'll look into this.

Thanks.

**Comment by mjauvin** [comment] 2020-02-16 13:10
duplicate of #303

**Closed by mjauvin** 2020-02-16 13:10 UTC
Labels: duplicate
