### ISSUE TITLE
error "array_key_exists() expects parameter 2 to be array, null given", when updating a record

### ISSUE THREAD

**Issue by Mohmdthabet** [rainlab/translate-plugin#373] opened 2018-05-10 11:35 UTC
I get this error when trying to update a record.

> "array_key_exists() expects parameter 2 to be array, null given" on line 381 of /public_html/plugins/rainlab/translate/classes/TranslatableBehavior.php

it seems that when the original field language is empty the translation plugin returns this error when updating the record

please note that no error when adding 

here is the lines where the error comes from.

```
379 foreach ($this->translatableAttributes[$locale] as $key => $value) {
381            if (!array_key_exists($key, $this->translatableOriginals[$locale])) {
382                $dirty[$key] = $value;
383           }
384           elseif ($value != $this->translatableOriginals[$locale][$key]) {
385                $dirty[$key] = $value;
386           }
387 }
```

System build 431 Translate plugin v1.3.8

**Comment by the-specialist2005** [comment] 2018-05-10 12:30
i checked it again the error seems to be more specific for the last inserted record only

**Comment by the-specialist2005** [comment] 2018-05-10 12:41
i commented some lines and it seems to work

```
        foreach ($this->translatableAttributes[$locale] as $key => $value) {
            //if (!array_key_exists($key, $this->translatableOriginals[$locale])) {
            //    $dirty[$key] = $value;
            //}
            //elseif ($value != $this->translatableOriginals[$locale][$key]) {
            if ($value != $this->translatableOriginals[$locale][$key]) {
                $dirty[$key] = $value;
            }
        }
```

**Comment by LukeTowers** [comment] 2018-05-11 15:47
@the-specialist2005 are you able to come up with a fix and provide it in a PR?

**Comment by the-specialist2005** [comment] 2018-05-15 12:27
Sorry, i haven't found a solution, the approach of commenting lines fails to save any rich editor field, only text field are saved. and if the rich editor is not empty, nothing is saved in the secondary language.

**Comment by the-specialist2005** [comment] 2018-05-15 14:46
I replaced the plugin with older version no 1.2.11, the issue seems to be from Arabic text because in the old version it is json_encoded before saving in the database while the new version does not encode it.
I still can't find a solution for it.

**Comment by the-specialist2005** [comment] 2018-07-28 04:00
with the build is 437 and translation plugin version 1.3.8 no translation is being saved to the database at all 
it shows like this in "rainlab_translate_attributes" table:
{"title":"","description":"","units":null,"meta_title":"","meta_description":""}

this makes the plugin useless

**Comment by LukeTowers** [comment] 2018-07-28 07:50
@the-specialist2005 is this related to the issue with repeaters?

**Comment by mjauvin** [comment] 2018-12-23 15:19
@the-specialist2005 can you give more details of how you are using the plugin? Is that for a static page, a CMS page? also give an example on how to reproduce this.

**Comment by LukeTowers** [comment] 2019-04-06 05:29
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Closed by LukeTowers** 2019-04-06 05:29 UTC
Labels: Status: Response Needed, Type: Unconfirmed Bug
