### ISSUE TITLE
OCMS 2.x translate plugin create duplicate content due to the language url prefix

### ISSUE THREAD

**Issue by PubliAlex** [rainlab/translate-plugin#708] opened 2022-12-06 08:44 UTC
Hello,

I create this new issue cause I cannot reopen the issue #707 you closed maybe a little to fast and I cannot reopen it.

When translate plugin is enabled, a page can be accessed using 2 different urls (exemple when website defined to french) :

https://www.mywebsite.com/mypage
https://www.mywebsite.com/fr/mypage

This happens even if you have only one language defined in backoffice, and even if you don't have the multilingual component present on the page or layout. Just the fact to install translate plugin in enought to create that behavior.

It shouldn't do that because it create duplicate content.

**The problem occurs on October CMS 2.x, works well with the new multisite system of October CMS 3.x**

Best regards,

**Comment by daftspunk** [comment] 2022-12-18 23:42
Duplicate of #707

**Closed by daftspunk** 2022-12-18 23:42 UTC
