### ISSUE TITLE
attributesToArray does not work with translated jsonable attributes

### ISSUE THREAD

**Issue by tobias-kuendig** [rainlab/translate-plugin#485] opened 2019-05-21 04:31 UTC
I've got a model:

```php
class Product extends Model {
    public $jsonable = ['links'];
    public $translatable = ['links'];
    public $implement = ['@RainLab.Translate.Behaviors.TranslatableModel'];
}
```

When I do this...

```php
$p = Product::first();
$p->attributesToArray();
```

... everything works as expected. When I run...

```php
$p = Product::first();
$p->lang('fr')->attributesToArray();
```

... i get:

```
PHP Warning:  json_decode() expects parameter 1 to be string, array given in /(...)/vendor/october/rain/src/Database/Model.php on line 1115
```

It seems like the jsonable attributes are already turned into an array when loaded via the `trans` method. The subsequent call to `json_decode` in `Model.php` therefore fails.

https://github.com/octobercms/library/blob/master/src/Database/Model.php#L1115

**Comment by mjauvin** [comment] 2019-05-22 19:57
Hmm, this is caused by `loadTranslatableData()` in `behaviors/TranslatableModel.php`, It's decoding the values before returning it.

Try commenting out the json_decode() call in there just to see if that fixes the problem.

I'm sure this code is needed, so we'll need to investigate deeper.

**Comment by mjauvin** [comment] 2019-05-22 20:15
Maybe we should use a try/catch block in `library/src/Database/Model.php`, I am not sure how to prevent this double decoding.

**Comment by tobias-kuendig** [comment] 2019-05-23 05:51
This line seems to be the problem:
https://github.com/rainlab/translate-plugin/blob/master/classes/TranslatableBehavior.php#L165

Without it the `attributesToArray()` call works but obviously everything else is broken.

The simplest solution that comes to mind is to add a `is_array` check to the `attributesToArray` method:

```php
        foreach ($this->jsonable as $key) {
            if (
                !array_key_exists($key, $attributes) ||
                in_array($key, $mutatedAttributes)
            ) {
                continue;
            }

            // Prevent double decoding
            if (is_array($attributes[$key])) {
                continue;
            }

            $jsonValue = json_decode($attributes[$key], true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $attributes[$key] = $jsonValue;
            }
        }
```

**Comment by mjauvin** [comment] 2019-05-23 11:23
Yes, that would make the most sense.

Can you submit a PR for this @tobias-kuendig ?

**Comment by LukeTowers** [comment] 2019-05-24 06:15
@tobias-kuendig make it a `!is_string` check instead please

**Comment by tobias-kuendig** [comment] 2019-05-24 07:02
This fix is available in https://github.com/octobercms/library/pull/405

**Comment by bennothommo** [comment] 2019-06-07 06:00
Fixed by https://github.com/octobercms/library/pull/405.

**Closed by bennothommo** 2019-06-07 06:00 UTC
Labels: Status: Completed, Type: Bug
