### ISSUE TITLE
Cannot access protected property

### ISSUE THREAD

**Issue by gergo85** [rainlab/translate-plugin#493] opened 2019-06-25 07:30 UTC
I updated my website to latest version (October 455 and Translate 1.6.0) and I got the following error message when I wanted to save a form:

![error](https://user-images.githubusercontent.com/2959112/60078150-a9393f80-972b-11e9-8435-5974886b9d27.JPG)

**Comment by mjauvin** [comment] 2019-06-25 11:37
Please give more details so we can try to reproduce.

**Comment by gergo85** [comment] 2019-06-25 13:24
**Versions:**   
October: 455  
PHP: 7.3.6  
Translate: 1.6.0  

**Translate codes in model file:**
```
public $implement = ['RainLab.Translate.Behaviors.TranslatableModel'];
public $translatable = [
    'name',
    ['slug', 'index' => true],
    'summary',
    'content'
];
```

**Comment by mjauvin** [comment] 2019-06-25 13:51
ok, I use this everyday with latest versions and am not getting this error.

Care to show how to reproduce on our end?

**Comment by LukeTowers** [comment] 2019-06-25 15:55
@gergo85 what other plugins do you use? It looks like one of them is trying to extend the translate plugin in a way that is not supported.

**Comment by gergo85** [comment] 2019-06-26 08:10
I disabled the most of plugins, but it did not help.

![plugins](https://user-images.githubusercontent.com/2959112/60162437-cfc5ac00-97f9-11e9-82e5-4cbf5e5923ad.JPG)

**Comment by mjauvin** [comment] 2019-06-26 13:09
Must be an issue with your two plugins, then (Own, Content)

**Comment by mjauvin** [comment] 2019-11-30 19:35
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If the problem is still reproducible with latest version of plugin and core, please re-open the issue with more details on how to reproduce.

**Closed by mjauvin** 2019-11-30 19:35 UTC
Labels: Status: Response Needed, Status: Review Needed, Type: Unconfirmed Bug
