### ISSUE TITLE
Translate plugin does not save data in RelationController

### ISSUE THREAD

**Issue by roojai** [rainlab/translate-plugin#380] opened 2018-06-29 06:08 UTC
If I access a backend form for a model in the normal list then my multi-language data will save.

If I access that same form through a RelationController from another model's form, then only the data for the default language will save.

**Comment by LukeTowers** [comment] 2018-06-29 17:08
Duplicate of #209

**Closed by LukeTowers** 2018-06-29 17:08 UTC

**Comment by LukeTowers** [comment] 2019-03-16 04:34
Fixed by https://github.com/octobercms/october/commit/13d710b161bdf65a19f38f974c259bc4997a162c
