### ISSUE TITLE
Static Page -> Menu : translation not working

### ISSUE THREAD

**Issue by dunets** [rainlab/translate-plugin#249] opened 2017-04-17 15:58 UTC
There are no way to translate a [Static Page](http://octobercms.com/plugin/rainlab-pages) menu items...
![image](https://cloud.githubusercontent.com/assets/6217617/25094362/b91e614a-238e-11e7-83b5-e1e5825b1e7a.png)

**Comment by LukeTowers** [comment] 2017-04-17 16:18
Duplicate of #246, #213, https://github.com/rainlab/pages-plugin/issues/240, https://github.com/rainlab/pages-plugin/issues/222, and https://github.com/rainlab/pages-plugin/issues/190. Discussion continues in https://github.com/rainlab/pages-plugin/issues/190

Please search to see if issues has been reported before opening a new one in the future.

**Closed** 2017-04-17 16:18 UTC
Labels: duplicate
