### ISSUE TITLE
Translate plugin doesn't show message in "Update messages" section

### ISSUE THREAD

**Issue by emilhakobian** [rainlab/translate-plugin#536] opened 2020-01-08 20:43 UTC
I can see languages and translations in database. 
<img width="1440" alt="Screen Shot 2020-01-09 at 12 42 56 AM" src="https://user-images.githubusercontent.com/4651893/72014247-f40a4700-3278-11ea-8cb7-a24d2d61348b.png">

**Comment by mjauvin** [comment] 2020-01-08 20:46
Please, what version of October and Translate plugin are you using?
Can you provide more details?

**Comment by emilhakobian** [comment] 2020-01-08 21:27
Plugin version 1.6.2
October build Build 464

**Comment by mjauvin** [comment] 2020-01-08 21:29
Try disabling all plugins except Rainlab.Translate

I cannot reproduce this with same versions

**Comment by emilhakobian** [comment] 2020-01-08 21:34
I had following languages: 
1. English - en 
2. Russian - ru
3. Armenian - am

Then I have added new languages 
4. English new - en-US
5. Russian new - ru-RU
6. Armenian new - am-HY
And removed old ones. 
Then renamed 4,5,6 to en, ru, am accordingly.
Even after changing codes back to initial state I'm still facing this issue.

**Comment by bennothommo** [comment] 2020-01-09 02:15
@emilhakobian Would you mind checking if there's any JavaScript issues being thrown in your browser console? Also, double-check if any messages are being added to the `storage/logs/debug.log` that might give an indicator as to what is occurring.

**Comment by emilhakobian** [comment] 2020-01-09 07:22
There are no errors in my console (see attachment), also there is no debug.log in storage/logs although my application debug mode set to **true**, I can see only the system.log.

![out](https://user-images.githubusercontent.com/4651893/72046589-314ef300-32d2-11ea-82da-cb098e84eeb2.gif)

**Comment by emilhakobian** [comment] 2020-01-09 19:10
Any news on this? 
I have re-installed all translation and translation-related plugins, still the same.

**Comment by mjauvin** [comment] 2020-01-09 19:26
I think it's related to issue #231 ... since you removed the default language, the translations have been lost.

**Comment by emilhakobian** [comment] 2020-01-09 19:35
So what should I do now?

**Comment by mjauvin** [comment] 2020-01-09 19:48
Either restore from db, and RENAME the languages instead of adding new / deleting old

**Comment by mjauvin** [comment] 2020-01-09 19:48
Or redo the translations

**Comment by emilhakobian** [comment] 2020-01-09 19:56
I have uninstalled the plugin and installed it again.  Why the behavior is not the same as when I first time installed the plugin?

**Comment by mjauvin** [comment] 2020-01-10 21:14
Did you restore your database ?

**Comment by mjauvin** [comment] 2020-01-10 21:15
duplicate of #231

**Comment by emilhakobian** [comment] 2020-01-10 21:24
What do you mean restore the database? Could you explain this in detail?

**Comment by mjauvin** [comment] 2020-01-10 23:02
If you have MySQL Database backups that were done BEFORE you changed the default language, you can restore the database from the backup to recover your translations.

Otherwise, you'll need to redo the translation from scratch.

**Comment by emilhakobian** [comment] 2020-01-14 15:13
Hi, 
I have figured out that I have no  DB backup. Could you tell me what you mean by saying "redo the translation from scratch"?
Because I have removed all translations and uninstalled plugin. After Installation, I found the same issues. - No translation keys (and no way to scan messages)
- No way to change the language in Blog, News, title, etc.

**Comment by mjauvin** [comment] 2020-01-14 17:08
Then I suggest disabling all plugins to make sure nothing is interfering with the default Translate plugin behavior.

**Comment by emilhakobian** [comment] 2020-01-14 17:19
Unfortunately the same ! 
![image](https://user-images.githubusercontent.com/4651893/72366363-8eeca080-3713-11ea-9ad8-29ceba519bde.png)

**Comment by mjauvin** [comment] 2020-01-14 17:23
Something is not right in your setup, you should AT LEAST have a header at the top of that page as shown in the screenshot below:

![Screenshot from 2020-01-14 12-23-03](https://user-images.githubusercontent.com/2013630/72366659-b2d6c480-36c8-11ea-864f-85632ed3200c.png)

**Comment by mjauvin** [comment] 2020-01-14 17:24
What version of October are you running?

**Comment by emilhakobian** [comment] 2020-01-14 17:26
464

**Comment by mjauvin** [comment] 2020-01-14 17:27
Do you get the same behavior in other browsers (would be better if no extensions are installed in the browser for this test).

**Comment by mjauvin** [comment] 2020-01-14 17:28
Something is definitely interfering with the rendering of that page. Did you tweak anything in config/* or elsewhere!?

**Comment by emilhakobian** [comment] 2020-01-14 17:46
Same in other browsers and even on another computer. 
I've found that there is a database row in backend_user_preferences table : 

id	user_id	namespace	group	item	         value
10	1	        backend	        hints	hidden	{"translation_messages_hint":1}

When I delete this row
<img width="800" alt="Screen Shot 2020-01-14 at 9 41 22 PM" src="https://user-images.githubusercontent.com/4651893/72367961-93668880-3716-11ea-9cd8-407cc6b2f679.png">

When I close the message(hint) I can see mesages and even translate them. 
<img width="1440" alt="Screen Shot 2020-01-14 at 9 41 45 PM" src="https://user-images.githubusercontent.com/4651893/72368009-ad07d000-3716-11ea-85e3-e958f2070666.png">

Once I refresh the page messages table is not rendering.
Also the content area in blog post is without content and without Language picker.

**Comment by mjauvin** [comment] 2020-01-14 17:49
I have NO IDEA. @daftspunk @LukeTowers @bennothommo ?

**Comment by LukeTowers** [comment] 2020-01-14 22:34
@emilhakobian are you using symlinks anywhere in your installation?

**Comment by mic8** [comment] 2020-02-17 07:56
> Same in other browsers and even on another computer.
> I've found that there is a database row in backend_user_preferences table :
> 
> id user_id namespace group item value
> 10 1 backend hints hidden {"translation_messages_hint":1}
> 
> When I delete this row
> <img alt="Screen Shot 2020-01-14 at 9 41 22 PM" width="800" src="https://user-images.githubusercontent.com/4651893/72367961-93668880-3716-11ea-9cd8-407cc6b2f679.png">
> 
> When I close the message(hint) I can see mesages and even translate them.
> <img alt="Screen Shot 2020-01-14 at 9 41 45 PM" width="1440" src="https://user-images.githubusercontent.com/4651893/72368009-ad07d000-3716-11ea-85e3-e958f2070666.png">
> 
> Once I refresh the page messages table is not rendering.
> Also the content area in blog post is without content and without Language picker.

Same issue here, any updates for this issue?

**Comment by mjauvin** [comment] 2020-02-17 12:34
@mic8 are you using symboluc links anywhere in your october installation?

**Comment by mic8** [comment] 2020-02-17 13:02
@mjauvin what kind of symbolic links?

**Comment by mjauvin** [comment] 2020-02-17 13:11
only one kind I know of.

is this happening on a fresh install of October?

**Comment by mic8** [comment] 2020-02-17 13:59
I don't think there are any symbolic links like that on fresh install of October

**Comment by mjauvin** [comment] 2020-02-17 14:08
No, there aren't, that's why we're asking if you added any because that might break things.

**Comment by bennothommo** [comment] 2020-02-17 14:39
@mic8 @emilhakobian I can confirm I've had no issues loading the Translate table, even following the instructions provided earlier.

The only way I can replicate this is either by using a symlink to the Translate plugin (storing the plugin files outside of the project folder) and having the config variable `cms.restrictBaseDir` set to `true`, or by faking a JavaScript error during the load process of the page.

We need more information from you both in order to try and ascertain where this fault is occurring. Things such as:
- Was the Translate plugin working fine at one point? When did you notice that it had stopped working?
- Are there any JavaScript error messages being thrown?
- Are any of the JavaScript resources not being loaded due to a server error?
- Is there any logs in `storage/logs/system.log` being added when the Translate page being loaded?
- Which web server are you using? Which PHP version are you using?

**Comment by mjauvin** [comment] 2020-03-15 06:50
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by joeinnes** [comment] 2020-09-06 15:07
For future internauts running into this issue, I found it was introduced to my site when I enabled Rocket Loader on Cloudflare. After disabling Rocket Loader, this issue waas fixed.

**Comment by mjauvin** [comment] 2020-09-06 15:48
@joeinnes any idea what's actually causing this in Rocket Loader?

**Comment by joeinnes** [comment] 2020-09-06 15:50
No idea, but it's not the first time Rocket Loader has mangled JS for me and I'm happy just turning it off rather than spending time diagnosing it :)

**Comment by LukeTowers** [comment] 2020-09-06 19:24
@mjauvin @bennothommo perhaps we should look at adding the rocketloader ignore syntax on all assets loaded by the backend addJs methods. I thought we already did that but it might have been only for core JS

**Comment by mjauvin** [comment] 2020-09-06 19:33
@LukeTowers I guess. Where do you see this for core JS ?

**Comment by mjauvin** [comment] 2020-09-06 19:56
@LukeTowers So you're suggesting adding `data-cfasync="false"` to all <script> tag added with addJs ?

ref. https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-my-script-s-in-Automatic-Mode-

**Comment by mjauvin** [comment] 2020-09-06 20:02
Curently, I see it in here only:
```
plugins/r4l/test/skins/layouts/auth.htm:            <script data-cfasync="false" src="<?= $script . '?v=' . $coreBuild; ?>" importance="high"></script>
modules/backend/layouts/auth.htm:            <script data-cfasync="false" src="<?= $script . '?v=' . $coreBuild; ?>" importance="high"></script>
modules/backend/layouts/_head.htm:    <script data-cfasync="false" src="<?= $script . '?v=' . $coreBuild; ?>" importance="high"></script>
```

**Comment by mjauvin** [comment] 2020-09-06 20:10
Something like this maybe?
```
diff --git a/modules/system/traits/AssetMaker.php b/modules/system/traits/AssetMaker.php
index 4918872e..94b09d3c 100644
--- a/modules/system/traits/AssetMaker.php
+++ b/modules/system/traits/AssetMaker.php
@@ -90,6 +90,7 @@ trait AssetMaker
             foreach ($this->assets['js'] as $asset) {
                 $attributes = Html::attributes(array_merge(
                     [
+                        'data-cfasync' => "false",
                         'src' => $this->getAssetEntryBuildPath($asset)
                     ],
                     array_except($asset['attributes'], $reserved)
```

**Comment by mjauvin** [comment] 2020-09-06 22:04
@joeinnes if you could re-enable Rocket Loader for your cloudflare and test with this fix to see if that works, that'd be appreciated.

**Comment by bennothommo** [comment] 2020-09-07 01:00
@mjauvin @LukeTowers I believe when this came up last time, I put forward my opinion that we shouldn't be adding these tags in. It's a specific hack for a third-party system, and it sets a precedent that we'll do this for other CDNs if they become popular enough. I would rather people configure the third-party system correctly by either telling it to ignore all Backend URLs, or creating a plugin which does what @mjauvin is suggesting.

**Comment by LukeTowers** [comment] 2020-09-07 03:17
@bennothommo @mjauvin ah that's right, I remember now. What we did was implement an event so that a third party plugin could do this for us. @emilhakobian @joeinnes @mic8 if you're using CloudFlare Rocket Loader, please install https://octobercms.com/plugin/heathdutton-cloudflare

**Closed by LukeTowers** 2020-09-07 03:17 UTC
Labels: Status: Response Needed, Type: Bug

**Comment by joeinnes** [comment] 2020-09-07 11:36
Also agree with this approach, I don't think it's October's responsibility to make sure third party tools don't mangle the UI. 

Just wanted to drop a note on this in this thread in case anyone is banging their head against a wall in future trying to work it out.
