### ISSUE TITLE
Translating a string containing a single quote

### ISSUE THREAD

**Issue by WebShapedBiz** [rainlab/translate-plugin#511] opened 2019-09-13 06:06 UTC
Hi,

I'm unable to figure out how to translate a string that has a single quote in it, for example, _O'Reilly Media - Technology and Business Training_. Wrapping the string in double-quotes doesn't work.
For the moment I'm using backticks but that's not nice to see.

Cheers.

**Comment by LukeTowers** [comment] 2019-09-13 23:33
@WebShapedBiz can you provide an example of what you're trying to do right now?

**Comment by WebShapedBiz** [comment] 2019-09-14 04:05
Hi, @LukeTowers. I gave a generic example with _O'Reilly Media_ but my real project is for one _B'nai B'rith_ lodge, and I'm getting exceptions every time I have a translation string containing _B'nai B'rith_, like this:
`{{ 'B'nai B'rith lodge'|_ }}`

I tried using double quotes and escaping the single quote within the string but without success.

Thank you for your time and effort.

**Comment by LukeTowers** [comment] 2019-09-14 11:44
@WebShapedBiz so `{{ 'B\'nai B\'rith lodge'|_ }}` doesn't work?

**Comment by WebShapedBiz** [comment] 2019-09-14 12:37
@LukeTowers your suggestion kinda works with the following issues:
1. It just converts single quotes to backticks on the front-end
2. It messes up syntax highlighting in the backend editor, and for that reason, I didn't at first even try with escaping the single-quote, seeing the messed up code editor.

**Comment by LukeTowers** [comment] 2019-09-19 16:29
@WebShapedBiz so `{{ "B'nai B'rith lodge"|_ }}` doesn't work either?

**Comment by WebShapedBiz** [comment] 2019-09-19 17:40
This, `{{ "B'nai B'rith lodge"|_ }}`, will work, but with converting a single quote to backticks. I made a screenshot of the webpage for you, where the upper text is rendered without translation, just `<h1>About B'nai B'rit lodge "Gavro Schwartz" Zagreb</h1>`
and there you can see single quotes rendered as they should be.
The lower text is generated with
`<h1>{{ "About B'nai B'rit lodge \"Gavro Schwartz\" Zagreb"|_ }}</h1>`
and you can see there that all the single quotes are rendered as backticks.
![Slika zaslona 2019-09-19 19 34 29](https://user-images.githubusercontent.com/6765137/65267233-e8054880-db14-11e9-90c1-e081f107a9bd.jpeg)

**Comment by mjauvin** [comment] 2019-09-20 17:40
@WebShapedBiz I tried to reproduce with the following, and it worked as expected in my case:

    <h1>{{ "B'nai B'rith lodge"|_ }}</h1>

This appeared in the "Translate messages" admin page and I was able to add a translation for it. When switching locale on the website, it also properly shows both translations.

What version are you using for October & Rainlab.Translate?

**Comment by WebShapedBiz** [comment] 2019-09-20 17:43
Hi @mjauvin. I'm using the latest versions of both, CMS v1.0.458 and Rainlab.Translate v1.6.2

**Comment by mjauvin** [comment] 2019-09-20 17:55
You may want to check your database, there may be a leftover entry when you used the "escaped" single quote which is interfering with the double quoted version of the string.

You may also want to try checking the "Purge all messages first" when scanning for messages, that may also solve the issue.

**Comment by WebShapedBiz** [comment] 2019-09-20 19:45
I did browse through the database hoping to find a little devil but without any luck. Purging all messages is my last resort since I'm lazy to redo all the translation because I'm thinking that export/import may also export/import the problem.
Anyhow, thank you for your time and effort in helping me. Tomorrow I'll continue this investigation.

Cheers.

**Comment by mjauvin** [comment] 2019-09-26 01:42
Closing this as we were not able to reproduce. Please re-open if you have more details that can help reproduce this.

**Closed by mjauvin** 2019-09-26 01:42 UTC
Labels: Status: Response Needed, Status: Review Needed, Type: Unconfirmed Bug
