### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by Pixinside** [rainlab/translate-plugin#681] opened 2022-06-13 13:09 UTC
I get a 404 error when switching languages on some pages. 
I've got to different slugs ( rooturl.com/fr/vente and rooturl.com/en/listings).
But the weird thing, is that it works just fine when I empty the cache.
I can't figure out why and how resolve it. Running octo 3.0.43 with translate 1.10.1.

Any hints?

**Comment by georgij-** [comment] 2022-06-17 12:55
Facing the same issue, running OctoberCMS 2.1.11 and Translate 1.11.1

**Comment by daftspunk** [comment] 2022-06-18 00:02
Hello,

Would love to help, but cannot seem to reproduce this using the `RainLab.Bonjour` theme:

![oc2-translate-url](https://user-images.githubusercontent.com/1392869/174413763-3fe003ba-108d-4611-9541-aa3822517b9d.gif)

1. `php artisan theme:install rainlab.bonjour`
1. Created Italian language
1. Translated some strings
1. Navigated to Static Pages > Content > Models page
1. Changed the Italian URL to `/content/booboo`

All working as above. Could it be a plugin issue? We can investigate with clear instructions to reproduce the problem.

Tested using OCMS v2.2.29 and Translate v1.11.1

**Comment by Pixinside** [comment] 2022-08-31 07:50
https://user-images.githubusercontent.com/1736427/187622800-785d6757-adad-4447-8770-e77aa156fec5.mp4

it seems that there is an issue with the slug and cache. But I cannot figure it out.

**Comment by daftspunk** [comment] 2022-09-08 23:44
Hey @Pixinside and @georgij-  

Apologies for the issue. It is difficult to see why this happens from the screenshot and also difficult to fix without reproducing it from a clean install. This should be fixed in the upcoming v3.1 OCMS release (#694) since most of the Translation code has been rewritten to escape the complexity of the current system. It should be ready in about a month or so.

**Comment by daftspunk** [comment] 2022-10-06 03:47
Still unable to replicate this in the latest version. We may need to look at your individual environment. If you still need help, please get in touch with the support desk for assistance: https://octobercms.com/contact

Thank you

**Closed by daftspunk** 2022-10-06 03:47 UTC
Labels: Type: Unconfirmed Bug
